In [1]:
import numpy as np

# Crear dos matrices 3x3 con números aleatorios entre 1 y 10
matriz1 = np.random.randint(1, 11, (3, 3))
matriz2 = np.random.randint(1, 11, (3, 3))

print("Matriz 1:\n", matriz1)
print("Matriz 2:\n", matriz2)

# Suma de ambas matrices
suma = matriz1 + matriz2
print("\nSuma de las matrices:\n", suma)

# Resta de la segunda matriz de la primera
resta = matriz1 - matriz2
print("\nResta de la segunda matriz de la primera:\n", resta)

# Multiplicación de la primera matriz por 2
multiplicacion_escalar = matriz1 * 2
print("\nPrimera matriz multiplicada por 2:\n", multiplicacion_escalar)

# Multiplicación matricial entre las dos matrices
multiplicacion_matricial = np.dot(matriz1, matriz2)
print("\nMultiplicación matricial de las dos matrices:\n", multiplicacion_matricial)


Matriz 1:
 [[10  2  8]
 [ 3 10  3]
 [ 9  3  3]]
Matriz 2:
 [[ 5  1  3]
 [ 6  4  6]
 [ 3  9 10]]

Suma de las matrices:
 [[15  3 11]
 [ 9 14  9]
 [12 12 13]]

Resta de la segunda matriz de la primera:
 [[ 5  1  5]
 [-3  6 -3]
 [ 6 -6 -7]]

Primera matriz multiplicada por 2:
 [[20  4 16]
 [ 6 20  6]
 [18  6  6]]

Multiplicación matricial de las dos matrices:
 [[ 86  90 122]
 [ 84  70  99]
 [ 72  48  75]]
